; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Test floating point arithmetic.
;
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -m88k-enable-delay-slot-filler=false | FileCheck --check-prefixes=CHECK,MC88100 %s
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88110 -m88k-enable-delay-slot-filler=false | FileCheck --check-prefixes=CHECK,MC88110 %s

define float @trunc(double %a) {
; MC88100-LABEL: trunc:
; MC88100:       | %bb.0:
; MC88100-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; MC88100-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; MC88100-NEXT:    fsub.sds %r2, %r2, %r0
; MC88100-NEXT:    jmp %r1
;
; MC88110-LABEL: trunc:
; MC88110:       | %bb.0:
; MC88110-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; MC88110-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; MC88110-NEXT:    fcvt.sd %r2, %r2
; MC88110-NEXT:    jmp %r1
  %trnc = fptrunc double %a to float
  ret float %trnc
}

define double @extend(float %a) {
; MC88100-LABEL: extend:
; MC88100:       | %bb.0:
; MC88100-NEXT:    fsub.dss %r2, %r2, %r0
; MC88100-NEXT:    jmp %r1
;
; MC88110-LABEL: extend:
; MC88110:       | %bb.0:
; MC88110-NEXT:    fcvt.ds %r2, %r2
; MC88110-NEXT:    jmp %r1
  %ext = fpext float %a to double
  ret double %ext
}

define float @negate1(float %a) {
; CHECK-LABEL: negate1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    xor.u %r2, %r2, 32768
; CHECK-NEXT:    jmp %r1
  %neg = fneg float %a
  ret float %neg
}

define double @negate2(double %a) {
; CHECK-LABEL: negate2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    xor %r3, %r3, 0
; CHECK-NEXT:    xor.u %r2, %r2, 32768
; CHECK-NEXT:    jmp %r1
; BUG!!! r3 is zero'ed - why?
  %neg = fneg double %a
  ret double %neg
}

define i32 @f32tosi32(float %a) {
; CHECK-LABEL: f32tosi32:
; CHECK:       | %bb.0:
; CHECK-NEXT:    trnc.ss %r2, %r2
; CHECK-NEXT:    jmp %r1
  %trnc = fptosi float %a to i32
  ret i32 %trnc
}

define i32 @f64tosi32(double %a) {
; CHECK-LABEL: f64tosi32:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    trnc.sd %r2, %r2
; CHECK-NEXT:    jmp %r1
  %trnc = fptosi double %a to i32
  ret i32 %trnc
}

define i64 @f32tosi64(float %a) {
; CHECK-LABEL: f32tosi64:
; CHECK:       | %bb.0:
; CHECK-NEXT:    subu %r31, %r31, 16
; CHECK-NEXT:    st %r30, %r31, 0
; CHECK-NEXT:    addu %r30, %r31, 0
; CHECK-NEXT:    st %r14, %r30, 4 | 4-byte Folded Spill
; CHECK-NEXT:    or %r14, %r0, %r1
; CHECK-NEXT:    bsr __fixsfdi
; CHECK-NEXT:    or %r1, %r0, %r14
; CHECK-NEXT:    ld %r14, %r30, 4 | 4-byte Folded Reload
; CHECK-NEXT:    ld %r30, %r30, 0 | 4-byte Folded Reload
; CHECK-NEXT:    addu %r31, %r31, 16
; CHECK-NEXT:    jmp %r1
  %trnc = fptosi float %a to i64
  ret i64 %trnc
}

define i64 @f64tosi64(double %a) {
; CHECK-LABEL: f64tosi64:
; CHECK:       | %bb.0:
; CHECK-NEXT:    subu %r31, %r31, 16
; CHECK-NEXT:    st %r30, %r31, 0
; CHECK-NEXT:    addu %r30, %r31, 0
; CHECK-NEXT:    st %r14, %r30, 4 | 4-byte Folded Spill
; CHECK-NEXT:    or %r14, %r0, %r1
; CHECK-NEXT:    bsr __fixdfdi
; CHECK-NEXT:    or %r1, %r0, %r14
; CHECK-NEXT:    ld %r14, %r30, 4 | 4-byte Folded Reload
; CHECK-NEXT:    ld %r30, %r30, 0 | 4-byte Folded Reload
; CHECK-NEXT:    addu %r31, %r31, 16
; CHECK-NEXT:    jmp %r1
  %trnc = fptosi double %a to i64
  ret i64 %trnc
}

define float @fadd1(float %a, float %b) {
; CHECK-LABEL: fadd1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fadd.sss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fadd float %a, %b
  ret float %sum
}

define float @fadd2(float %a, double %b) {
; CHECK-LABEL: fadd2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fadd.ssd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fadd double %ext, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fadd3(double %a, float %b) {
; CHECK-LABEL: fadd3:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fadd.sds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fadd double %a, %ext
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fadd4(double %a, double %b) {
; CHECK-LABEL: fadd4:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fadd.sdd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fadd double %a, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define double @fadd5(double %a, double %b) {
; CHECK-LABEL: fadd5:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fadd.ddd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fadd double %a, %b
  ret double %sum
}

define double @fadd6(double %a, float %b) {
; CHECK-LABEL: fadd6:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fadd.dds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fadd double %a, %ext
  ret double %sum
}

define double @fadd7(float %a, double %b) {
; CHECK-LABEL: fadd7:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fadd.dsd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fadd double %ext, %b
  ret double %sum
}

define double @fadd8(float %a, float %b) {
; CHECK-LABEL: fadd8:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fadd.dss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fadd float %a, %b
  %ext = fpext float %sum to double
  ret double %ext
}

define float @fsub1(float %a, float %b) {
; CHECK-LABEL: fsub1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fsub.sss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fsub float %a, %b
  ret float %sum
}

define float @fsub2(float %a, double %b) {
; CHECK-LABEL: fsub2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fsub.ssd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fsub double %ext, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fsub3(double %a, float %b) {
; CHECK-LABEL: fsub3:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fsub.sds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fsub double %a, %ext
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fsub4(double %a, double %b) {
; CHECK-LABEL: fsub4:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fsub.sdd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fsub double %a, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define double @fsub5(double %a, double %b) {
; CHECK-LABEL: fsub5:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fsub.ddd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fsub double %a, %b
  ret double %sum
}

define double @fsub6(double %a, float %b) {
; CHECK-LABEL: fsub6:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fsub.dds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fsub double %a, %ext
  ret double %sum
}

define double @fsub7(float %a, double %b) {
; CHECK-LABEL: fsub7:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fsub.dsd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fsub double %ext, %b
  ret double %sum
}

define double @fsub8(float %a, float %b) {
; CHECK-LABEL: fsub8:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fsub.dss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fsub float %a, %b
  %ext = fpext float %sum to double
  ret double %ext
}

define float @fmul1(float %a, float %b) {
; CHECK-LABEL: fmul1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fmul.sss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fmul float %a, %b
  ret float %sum
}

define float @fmul2(float %a, double %b) {
; CHECK-LABEL: fmul2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fmul.ssd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fmul double %ext, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fmul3(double %a, float %b) {
; CHECK-LABEL: fmul3:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fmul.sds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fmul double %a, %ext
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fmul4(double %a, double %b) {
; CHECK-LABEL: fmul4:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fmul.sdd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fmul double %a, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define double @fmul5(double %a, double %b) {
; CHECK-LABEL: fmul5:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fmul.ddd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fmul double %a, %b
  ret double %sum
}

define double @fmul6(double %a, float %b) {
; CHECK-LABEL: fmul6:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fmul.dds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fmul double %a, %ext
  ret double %sum
}

define double @fmul7(float %a, double %b) {
; CHECK-LABEL: fmul7:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fmul.dsd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fmul double %ext, %b
  ret double %sum
}

define double @fmul8(float %a, float %b) {
; CHECK-LABEL: fmul8:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fmul.dss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fmul float %a, %b
  %ext = fpext float %sum to double
  ret double %ext
}

define float @fdiv1(float %a, float %b) {
; CHECK-LABEL: fdiv1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fdiv.sss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fdiv float %a, %b
  ret float %sum
}

define float @fdiv2(float %a, double %b) {
; CHECK-LABEL: fdiv2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fdiv.ssd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fdiv double %ext, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fdiv3(double %a, float %b) {
; CHECK-LABEL: fdiv3:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fdiv.sds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fdiv double %a, %ext
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define float @fdiv4(double %a, double %b) {
; CHECK-LABEL: fdiv4:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fdiv.sdd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fdiv double %a, %b
  %trnc = fptrunc double %sum to float
  ret float %trnc
}

define double @fdiv5(double %a, double %b) {
; CHECK-LABEL: fdiv5:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fdiv.ddd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %sum = fdiv double %a, %b
  ret double %sum
}

define double @fdiv6(double %a, float %b) {
; CHECK-LABEL: fdiv6:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r3 killed $r3 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    | kill: def $r2 killed $r2 killed $r2_r3 def $r2_r3
; CHECK-NEXT:    fdiv.dds %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %b to double
  %sum = fdiv double %a, %ext
  ret double %sum
}

define double @fdiv7(float %a, double %b) {
; CHECK-LABEL: fdiv7:
; CHECK:       | %bb.0:
; CHECK-NEXT:    | kill: def $r5 killed $r5 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    | kill: def $r4 killed $r4 killed $r4_r5 def $r4_r5
; CHECK-NEXT:    fdiv.dsd %r2, %r2, %r4
; CHECK-NEXT:    jmp %r1
  %ext = fpext float %a to double
  %sum = fdiv double %ext, %b
  ret double %sum
}

define double @fdiv8(float %a, float %b) {
; CHECK-LABEL: fdiv8:
; CHECK:       | %bb.0:
; CHECK-NEXT:    fdiv.dss %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %sum = fdiv float %a, %b
  %ext = fpext float %sum to double
  ret double %ext
}
