; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88110 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s

define ptr @fp0() nounwind {
; CHECK-LABEL: fp0:
; CHECK:       | %bb.0:
; CHECK-NEXT:    subu %r31, %r31, 16
; CHECK-NEXT:    st %r30, %r31, 0 | 4-byte Folded Spill
; CHECK-NEXT:    addu %r30, %r31, 0
; CHECK-NEXT:    or %r2, %r0, %r30
; CHECK-NEXT:    ld %r30, %r31, 0 | 4-byte Folded Reload
; CHECK-NEXT:    addu %r31, %r31, 16
; CHECK-NEXT:    jmp %r1
  %fp = tail call ptr @llvm.frameaddress(i32 0)
  ret ptr %fp
}

define ptr @fp1() nounwind {
; CHECK-LABEL: fp1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    subu %r31, %r31, 16
; CHECK-NEXT:    st %r30, %r31, 0 | 4-byte Folded Spill
; CHECK-NEXT:    addu %r30, %r31, 0
; CHECK-NEXT:    ld %r2, %r30, 0
; CHECK-NEXT:    ld %r30, %r31, 0 | 4-byte Folded Reload
; CHECK-NEXT:    addu %r31, %r31, 16
; CHECK-NEXT:    jmp %r1
  %fp = tail call ptr @llvm.frameaddress(i32 1)
  ret ptr %fp
}

define ptr @fp2() nounwind {
; CHECK-LABEL: fp2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    subu %r31, %r31, 16
; CHECK-NEXT:    st %r30, %r31, 0 | 4-byte Folded Spill
; CHECK-NEXT:    addu %r30, %r31, 0
; CHECK-NEXT:    ld %r2, %r30, 0
; CHECK-NEXT:    ld %r2, %r2, 0
; CHECK-NEXT:    ld %r30, %r31, 0 | 4-byte Folded Reload
; CHECK-NEXT:    addu %r31, %r31, 16
; CHECK-NEXT:    jmp %r1
  %fp = tail call ptr @llvm.frameaddress(i32 2)
  ret ptr %fp
}
