; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; Test constant folding of intrinsics.
;
; RUN: opt -S -mtriple=m88k-openbsd -O1 %s  | FileCheck %s

define i32 @f1() {
; CHECK-LABEL: define noundef i32 @f1(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    ret i32 3
;
  %res = tail call i32 @llvm.m88k.ff1(i32 3758096384)
  ret i32 %res
}

define i32 @f2() {
; CHECK-LABEL: define noundef i32 @f2(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:    ret i32 32
;
  %res = tail call i32 @llvm.m88k.ff1(i32 0)
  ret i32 %res
}

define i32 @f3() {
; CHECK-LABEL: define noundef i32 @f3(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:    ret i32 29
;
  %res = tail call i32 @llvm.m88k.ff0(i32 5)
  ret i32 %res
}

define i32 @f4() {
; CHECK-LABEL: define noundef i32 @f4(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:    ret i32 32
;
  %res = tail call i32 @llvm.m88k.ff0(i32 0)
  ret i32 %res
}

declare i32 @llvm.m88k.ff1(i32)
declare i32 @llvm.m88k.ff0(i32)
