; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
;
; Test intrinsics.
;
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88110 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s

define i32 @f1(i32 %x) {
; CHECK-LABEL: f1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    ff1 %r2, %r2
; CHECK-NEXT:    jmp %r1
  %res = tail call i32 @llvm.m88k.ff1(i32 %x)
  ret i32 %res
}

define i32 @f2(i32 %x) {
; CHECK-LABEL: f2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    ff0 %r2, %r2
; CHECK-NEXT:    jmp %r1
  %res = tail call i32 @llvm.m88k.ff0(i32 %x)
  ret i32 %res
}

declare i32 @llvm.m88k.ff1(i32)
declare i32 @llvm.m88k.ff0(i32)
