; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
;
; Test LD/ST combinations.
;
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88110 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s

define void @f1(ptr noundef %p1, ptr noundef %p2) {
; CHECK-LABEL: f1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    ld.b %r2, %r2, 0
; CHECK-NEXT:    st.b %r2, %r3, 0
; CHECK-NEXT:    jmp %r1
  %v = load i8, ptr %p1, align 1
  store i8 %v, ptr %p2, align 1
  ret void
}

define void @f2(ptr noundef %p1, ptr noundef %p2) {
; CHECK-LABEL: f2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    ld.h %r2, %r2, 0
; CHECK-NEXT:    st.h %r2, %r3, 0
; CHECK-NEXT:    jmp %r1
  %v = load i16, ptr %p1, align 2
  store i16 %v, ptr %p2, align 2
  ret void
}

define void @f3(ptr noundef %p1, ptr noundef %p2) {
; CHECK-LABEL: f3:
; CHECK:       | %bb.0:
; CHECK-NEXT:    ld %r2, %r2, 0
; CHECK-NEXT:    st %r2, %r3, 0
; CHECK-NEXT:    jmp %r1
  %v = load i32, ptr %p1, align 4
  store i32 %v, ptr %p2, align 4
  ret void
}
