; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; Test pointer arithmetic.
;
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -verify-machineinstrs -m88k-enable-delay-slot-filler=false | FileCheck --check-prefixes=CHECK,MC88100 %s
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88110 -verify-machineinstrs -m88k-enable-delay-slot-filler=false | FileCheck --check-prefixes=CHECK,MC88110 %s

declare ptr @llvm.ptrmask.p0.i32(ptr, i32)

define ptr @f1(ptr %p) {
; CHECK-LABEL: f1:
; CHECK:       | %bb.0:
; CHECK-NEXT:    clr %r2, %r2, 3<0>
; CHECK-NEXT:    jmp %r1
  %res = call ptr @llvm.ptrmask.p0.i32(ptr %p, i32 -8)
  ret ptr %res
}

; TODO lda should be generated here.
define ptr @f2(ptr %p, i32 %x) {
; CHECK-LABEL: f2:
; CHECK:       | %bb.0:
; CHECK-NEXT:    mak %r3, %r3, 0<2>
; CHECK-NEXT:    addu %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %arrayidx = getelementptr inbounds i32, ptr %p, i32 %x
  ret ptr %arrayidx
}

; TODO Result should be different - MC88110 has lda.d
define ptr @f3(ptr %p, i32 %x) {
; CHECK-LABEL: f3:
; CHECK:       | %bb.0:
; CHECK-NEXT:    mak %r3, %r3, 0<3>
; CHECK-NEXT:    addu %r2, %r2, %r3
; CHECK-NEXT:    jmp %r1
  %arrayidx = getelementptr inbounds i64, ptr %p, i32 %x
  ret ptr %arrayidx
}

define ptr @f4(ptr %p) {
; CHECK-LABEL: f4:
; CHECK:       | %bb.0:
; CHECK-NEXT:    and %r2, %r2, 65528
; CHECK-NEXT:    jmp %r1
  %asint = ptrtoint ptr %p to i32
  %aligned = and i32 %asint, -8
  %alignedptr = inttoptr i32 %aligned to ptr
  ret ptr %alignedptr
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; MC88100: {{.*}}
; MC88110: {{.*}}
