; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s

define void @func() {
; CHECK-LABEL: func:
; CHECK:       | %bb.0: | %entry
; CHECK-NEXT:    or.u %r10, %r0, 1
; CHECK-NEXT:    or %r10, %r10, 16
; CHECK-NEXT:    subu %r31, %r31, %r10
; CHECK-NEXT:    st %r1, %r31, 4 | 4-byte Folded Spill
; CHECK-NEXT:    st %r30, %r31, 0 | 4-byte Folded Spill
; CHECK-NEXT:    addu %r30, %r31, 0
; CHECK-NEXT:    add %r2, %r30, 16
; CHECK-NEXT:    bsr process
; CHECK-NEXT:    ld %r30, %r31, 0 | 4-byte Folded Reload
; CHECK-NEXT:    ld %r1, %r31, 4 | 4-byte Folded Reload
; CHECK-NEXT:    or.u %r10, %r0, 1
; CHECK-NEXT:    or %r10, %r10, 16
; CHECK-NEXT:    addu %r31, %r31, %r10
; CHECK-NEXT:    jmp %r1
entry:
  %data = alloca [16384 x i32], align 4
  call void @process(ptr noundef nonnull %data) #3
  ret void
}

declare void @process(ptr noundef)
