; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; Test ST instructions.
;
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88100 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=m88k-openbsd -mcpu=mc88110 -m88k-enable-delay-slot-filler=false -verify-machineinstrs | FileCheck %s

define void @f1(ptr %p) {
  store i32 0, ptr %p, align 1
  ret void
}

define void @f2(ptr %p) {
  store i32 0, ptr %p, align 2
  ret void
}

define void @f3(ptr %p, i32 %val) {
  store i32 %val, ptr %p, align 1
  ret void
}

define void @f4(ptr %p, i32 %val) {
  store i32 %val, ptr %p, align 2
  ret void
}

define void @f5(ptr %p, i32 %val) {
  %trunc = trunc i32 %val to i8
  store i8 %trunc, ptr %p, align 1
  ret void
}

define void @f6(ptr %p, i32 %val) {
  %trunc = trunc i32 %val to i16
  store i16 %trunc, ptr %p, align 1
  ret void
}


define void @f7(ptr %p, i32 %val) {
  %arrayidx = getelementptr inbounds i32, ptr %p, i32 2
  store i32 %val, ptr %p, align 1
  ret void
}


define void @f8(ptr %p, i32 %idx, i32 %val) {
  %arrayidx = getelementptr inbounds i32, ptr %p, i32 %idx
  store i32 %val, ptr %arrayidx, align 1
  ret void
}
