// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// REQUIRES: m88k-registered-target
// RUN: %clang_cc1 -target-cpu mc88100 -triple m88k-openbsd -Wall -Wno-unused -Werror -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -target-cpu mc88110 -triple m88k-openbsd -Wall -Wno-unused -Werror -emit-llvm -x c++ %s -o - | FileCheck %s

int __builtin_m88k_ff1(unsigned);
int __builtin_m88k_ff0(unsigned);

#ifdef __cplusplus
extern "C" {
#endif

// CHECK-LABEL: define dso_local i32 @ff1(
// CHECK-SAME: i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.m88k.ff1(i32 [[TMP0]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int ff1(unsigned x) {
  return __builtin_m88k_ff1(x);
}

// CHECK-LABEL: define dso_local i32 @ff0(
// CHECK-SAME: i32 noundef [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.m88k.ff0(i32 [[TMP0]]) #[[ATTR2]]
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int ff0(unsigned x) {
  return __builtin_m88k_ff0(x);
}

#ifdef __cplusplus
}
#endif
